### PR TITLE
fix: remove hardcoded architecture in zarf packages

### PR DESCRIPTION
**Pull request by zachariahmiller**
remove arch in zarf.yamls
support lower footprint dev deploy
add flavor matrix to publish step
remove unused images (from disabled dep charts) from zarf.yaml
add `only.cluster.architecture: amd64` to registry1 flavor

### CODE REVIEW

**Comment by zachariahmiller** [comment]
The current registry1 pipeline is passing on this and the upstream amd64 is deploying successfully on my homelab I havent been able to verify arm yet, see previous comment.

**Comment by zachariahmiller** [comment]
Wasn't able to get darwin arm deploying including when i reduced the requests and replicas based on this https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/examples/values-gke-minimum.yaml and some trial and error. 

IIRC is was the webservice container wouldnt come up fully and there were 502 errors trying to hit the health check endpoint on the istio proxy sidecar.  

FWIW, at least without istio, gitlab expects one to be able to develop on m series mac w/ colima with far less resources than i was using. Even adding the specs in this list to what i was deploying all of uds core on previously wasnt working. https://docs.gitlab.com/charts/development/kind/#building-the-vm 

The config is the same regardless of arch and upstream is working on amd64. Outside of this context, istio is working on arm64, so not really sure what the culprit is here ☹️ 

It might be worth testing this on a graviton instance, or if we end up getting the arm runner beta access to confirm if this issue is seen on arm64 in general or if it is limited to darwin arm. It also might be worth testing the actual upstream gitlab chart instead of repo1 on top of k3d-istio with the uds package cr as that is the chart gitlab would expect to work with 4 cores and 16gb ram per the above link. 

I'm trying the test one more time with the request bumped up for the webservice and using the otherwise "minimal" config. Assuming that doesnt work I'll table this and clean up this PR to be merged.

**Comment by zachariahmiller** [comment]
Confirmed working on darwin_arm with the single server k3d config. 😎

**Comment by zachariahmiller** [comment]
This also completes https://github.com/defenseunicorns/uds-package-gitlab/issues/21

**Review by mjnagel — APPROVED** [review]
Yamllint does not like some things (trailing spaces, indentation, extra newlines, etc) but this LGTM and worked on my Mac.

**Comment by zachariahmiller** [comment]
thanks @mjnagel

**Comment by zachariahmiller** [comment]
created issue to add the lint check https://github.com/defenseunicorns/uds-package-gitlab/issues/31

**Pull request merged**
