### PR TITLE
feat: add BUCKET_PREFIX variable

### LINKED ISSUE #44: Allow BUCKET_PREFIX to be defined
### Is your feature request related to a problem? Please describe.
I do not want to use the prefix of `uds-` for buckets.

This is hardcoded here:
https://github.com/defenseunicorns/uds-package-gitlab/blob/42e1f96de45381d514ff475715a3f7d301c24c37/values/common-values.yaml#L49-L71

I'd like to be able to pass in a value for `BUCKET_PREFIX` to the [zarf.yaml](https://github.com/defenseunicorns/uds-package-gitlab/blob/main/zarf.yaml) also, this can default to `uds-` if needed.

### PR DESCRIPTION
**Pull request by zack-is-cool**
## Related Issue

Fixes #44
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-gitlab/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by anthonywendt** [comment]
I ran into the issue of our buckets missing that `uds` was added as a prefix to this new package version of gitlab when we switched to it. Is there a need for defining a prefix at all? I know we added the suffix back on the old capability. Or can we just remove the use of `uds` in the bucket names and only have the suffix?

**Comment by zack-is-cool** [comment]
For our IaC we have a pattern of adding a specific prefix and suffix for everything else, so the ability to do this works for our usecase. It was weird having everything else being named in a specific pattern, and then for these resources being restricted to using `uds-`.

We could default the prefix to `""` if that's preferable, just like suffix, or as the code is now you could set it to be `""` if you don't need/want a prefix. I'm fine with either solution.

Right now I'm working around this with 12 different overrides in my uds bundle for bucket names 😄

**Comment by justin-o12** [comment]
> I ran into the issue of our buckets missing that `uds` was added as a prefix to this new package version of gitlab when we switched to it. Is there a need for defining a prefix at all? I know we added the suffix back in the old capability. Or can we just remove the use of `uds` in the bucket names and only have the suffix?

I remember we went back and forth on this during one of our first efforts to deploy SWF on EKS.  Since buckets need to be globally unique, we had to use some sort of combination of suffix and prefix.  I think we ended up having the suffix as optional, which meant we needed a prefix.  We must have decided to stick with and hardcode `uds-` at that time.

Maybe the capability needs to not have an opinion and allow the consumer to use a prefix and/or a suffix.

**Comment by anthonywendt** [comment]
> I ran into the issue of our buckets missing that `uds` was added as a prefix to this new package version of gitlab when we switched to it. Is there a need for defining a prefix at all? I know we added the suffix back in the old capability. Or can we just remove the use of `uds` in the bucket names and only have the suffix?

That makes sense. I don't really care. I just need to pay attention so I set up and configure our buckets correctly when we use the package.

**Comment by anthonywendt** [comment]
> For our IaC we have a pattern of adding a specific prefix and suffix for everything else, so the ability to do this works for our usecase. It was weird having everything else being named in a specific pattern, and then for these resources being restricted to using `uds-`.
> 
> We could default the prefix to `""` if that's preferable, just like suffix, or as the code is now you could set it to be `""` if you don't need/want a prefix. I'm fine with either solution.
> 
> Right now I'm working around this with 12 different overrides in my uds bundle for bucket names 😄

That makes sense. Looks like fun haha! I don't really care. I just need to pay attention so I set up and configure our buckets correctly when we use the package.

**Comment by zachariahmiller** [comment]
yeah i think we need prefix and suffix. There will be times there are enforced naming conventions that have to be worked around and this better facilitates that, while also giving more customization options that can reduce the likelyhood of conflicts with globally unique names. I'm happy with this implementation (zarf var prefix default to uds-) as it wont be a breaking change.

**Review by zachariahmiller — APPROVED** [review]
🚢 🇮🇹

**Pull request merged**
