### PR TITLE
chore: migrate to uds-common shared actions and workflows

### PR DESCRIPTION
**Pull request by ericwyles**
## Description
Migrate save-logs, setup, and commitlint to use common actions and workflows from uds-common
...

## Related Issue

Relates to #39 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-gitlab/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by zachariahmiller** [comment]
@ericwyles I dont think we want to add them to common. For the zarf failure this is likely the same issue you ran into last week where embedded commands in the task need to be changed from `zarf` to `uds zarf`. At this time node shouldnt be needed for this project.

**Comment by ericwyles** [comment]
@zachariahmiller Thanks for that, good point. I'll go try to root out any references to bare 'zarf'.

**Comment by ericwyles** [comment]
This is still having an issue with commitlint workflow reference. Working on it...

**Comment by ericwyles** [comment]
@zachariahmiller I think this one is ready now.

**Comment by zachariahmiller** [comment]
@ericwyles okay I'll take a look in a bit. Cursory glance looks good. Looks like we will need to change the required check for the pr title the way this is implemented. Unfortunately, I dont think that's avoidable.

**Review by zachariahmiller — DISMISSED** [review]
@ericwyles i made a small tweak so the job name started with an uppercase letter to be consistent and updated the required check to reflect the new name now that its calling the common workflow. Will get someone else to approve since we both had commits, but this looks good to me.

**Review by mjnagel — APPROVED** [review]

**Pull request merged**
